### ISSUE TITLE
Sending E-Mails if Users are offline

### ISSUE THREAD

**Issue by chrisdevel** [Bearle/django_private_chat2#14]
Hi team,

I could not find a place in the views.py where messages are being written into the database. I would like to send an email from the backend, if a user has written a message, however the second user is offline.

Could you please tell me at which please the chat messages are being saved?

Many thanks.

**Comment by delneg** [comment]
Hey,
The fact is that views are merely for convenience (e.g. some people may not use them at all).
All the main logic is in consumers.py,
specifically
File message
https://github.com/Bearle/django_private_chat2/blob/master/django_private_chat2/consumers.py#L261
Text message
https://github.com/Bearle/django_private_chat2/blob/master/django_private_chat2/consumers.py#L316

The definitions
https://github.com/Bearle/django_private_chat2/blob/master/django_private_chat2/consumers.py#L111

Thanks for using the project !

**Comment by chrisdevel** [comment]
Hi delneg! Many thanks for your support - it seems I forgot to write you that this solved my issue! I appreciate your help!
