### ISSUE TITLE
JSON parse error while running

### ISSUE THREAD

**Issue by alexdrm98** [Bearle/django_private_chat2#15]
* django_private_chat2 version: latest
* Django version: 3.2.4
* Python version: 3.9
* Operating System: Linux

### Description

When ever i login, i get this annoying json parse error 
![image](https://imgur.com/vUj2WQs.png)

THE FULL LOG HERE: https://bpa.st/74OQ
Thank you guys!

**Comment by delneg** [comment]
Can you please provide more info ? I didn't see anything suspicious in server logs you provided, maybe there are some errors in frontend logs ?

Also, for the sake of experiment I did clone the repository, followed the exact steps in the `example/README.md` file and it worked absolutely fine.

**Comment by alexdrm98** [comment]
Meanwhile can I ask how can we change the background image to a white background colour?

**Comment by delneg** [comment]
You can find css for the example app frontend in 
https://github.com/Bearle/django_private_chat2/blob/master/example/frontend/src/App.css
The instructions on how to build are in the example/frontend README.
However, most of the times you'll probably want to build your own frontend.

**Comment by alexdrm98** [comment]
Apps only works better on 127.0.0.1:8000 and when we visit localhost:8000 it's an error. Also, I tried to make it work in LAN, using `python manage.py runserver 0.0.0.0:8000` and access it, we get this "failed to fetch error" to the user trying to access from 192.168.43.10 
Can I fix? Thanks!

**Comment by delneg** [comment]
Please see https://github.com/Bearle/django_private_chat2/issues/7

**Comment by alexdrm98** [comment]
I saw #7 and still have this question. 
My case is that I've a system with server running in my LAN. I'm trying to access the same from another system in LAN, basically http://192.168.10.10:8000, I can access it. But I get that "JSON fetch error" which I mentioned in this report. 
You mentioned this: "Edit: Please note that backend url is also hardcoded in the example app."
In the hardcoded value, http://127.0.0.1 , to what I should change to?

**Comment by alexdrm98** [comment]
Thanks!
