### ISSUE TITLE
User Dialogs Limit / User

### ISSUE THREAD

**Issue by chrisdevel** [Bearle/django_private_chat2#21]
Currently I have around 150 dialogs / user in DB, however not all dialogs are displayed in the chat app. After deleting some dialogs as admin, others dialogs appeared again. 

I was wondering if there is a limit as of dialogs per user?

**Comment by delneg** [comment]
You can see the pagination settings here:
for messages
https://github.com/Bearle/django_private_chat2/blob/master/django_private_chat2/views.py#L31
for dialogs
https://github.com/Bearle/django_private_chat2/blob/master/django_private_chat2/views.py#L60

**Comment by delneg** [comment]
Other than that I can't seem to find any limits on dialogs count.
You can make your own views easily anyway based on the above

**Comment by chrisdevel** [comment]
You are a genius - works as expected. Thanks a lot!
