### ISSUE TITLE
413 Request Entity Too Large for URL

### ISSUE THREAD

**Issue by chrisdevel** [Bearle/django_private_chat2#22]
Guys, I am getting the enclosed error when uploading specific files (also enclosed). I dont know if it has to do something with the extension, however jpeg and other files work perfectly fine. Its just that some do not work. I did not any kind of restriction (size, file extension). Also I dont know where the error is raised in the code. Any clue where to look at?

Many thanks - you guys are awesome! 

![413 Request Entity Too Large for URL](https://user-images.githubusercontent.com/6973582/145688274-9fe1b80c-f4e4-4fab-903a-e17bd1532038.png)

![IMG_20211211_170230](https://user-images.githubusercontent.com/6973582/145688275-9cb6625d-675d-4785-879b-63ec800965e3.jpg)

**Comment by Zagrebelin** [comment]
I think you have to check web-server (nginx, apache or something) configuration. Mostly this type of errors caused by server misconfiguration.

**Comment by delneg** [comment]
As you can see here https://github.com/Bearle/django_private_chat2/blob/master/django_private_chat2/views.py#L104
Currently, no file size limit is enforced.

**Comment by chrisdevel** [comment]
Thanks guys. Indeed it was the web-server config. Nginx limits the upload by default. In case anyone runs into the same error, I solved it adding these lines to the config: https://www.tecmint.com/limit-file-upload-size-in-nginx/
