### ISSUE TITLE
According to Quickstart configuration, no front-end page is opened

### ISSUE THREAD

**Issue by wangxr011235** [Bearle/django_private_chat2#37]
* django_private_chat2 version:1.0.2
* Django version:3.2
* Python version:3.7
* Operating System:windows

### Description

According to Quickstart configuration, no front-end page is opened

### What I Did

According to Quickstart configuration, no front-end page is opened.
![image](https://user-images.githubusercontent.com/50837958/178454914-3dfe84d0-bd90-4255-9795-b6ba687cb361.png)
ps:When will the new version be released？

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by 05ZT30** [comment]
use example folder's content instead of quik start
