### ISSUE TITLE
Why is no heartbeat？

### ISSUE THREAD

**Issue by CocoaML** [Bearle/django_private_chat2#8]

**Comment by delneg** [comment]
Please provide more information.
Do you mean that there should be some sort of pinging mechanism ?
If so, i believe it would be fine to implement it client-side only to keep tcp session alive (the server will respond as usual to any unknown message)

**Comment by CocoaML** [comment]
> Please provide more information.
> Do you mean that there should be some sort of pinging mechanism ?
> If so, i believe it would be fine to implement it client-side only to keep tcp session alive (the server will respond as usual to any unknown message)

Yeah, I have a problem with how to use the heartbeat to keep the connection state between the client and the server. If the client doesn't have a heartbeat, how can the server disconnect? Using the Django, channels.

**Comment by delneg** [comment]
I don't think that I understand the issue.
Right now the disconnect is handled normally by the browser (when websocket is closed) and in my time using the application I haven't encountered any issues related to client connectivity.
If you could explain your problem in detail, that would be great.

**Comment by delneg** [comment]
Closing as stale.
