### ISSUE TITLE
Change Example app

### ISSUE THREAD

**Issue by ovt00** [Bearle/django_private_chat2#9]
* django_private_chat2 version: 0.1.4
* Django version: 3.2.2
* Python version: 3.9.1
* Operating System: ubuntu

### Description

I can't build frontend app.

### What I Did
1. npm install -g yarn
2. sudo snap install dotnet-sdk --classic --channel=5.0
3. sudo snap alias dotnet-sdk.dotnet dotnet
4. sudo snap install dotnet-runtime-50 --classic
5. sudo snap alias dotnet-runtime-50.dotnet dotnet
6. export DOTNET_ROOT=/snap/dotnet-sdk/current
7. dotnet --list-sdks
5.0.203 [/snap/dotnet-sdk/126/sdk]
8. dotnet --list-runtimes
Microsoft.AspNetCore.App 5.0.6 [/snap/dotnet-sdk/126/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.6 [/snap/dotnet-sdk/126/shared/Microsoft.NETCore.App]
9. npm run start:fable
 chat@0.1.0 start:fable /home/dell/PycharmProjects/chat/web/frontend
> dotnet fable watch fs-src

Fable: F# to JS compiler 3.1.7
Thanks to the contributor! @worldbeater
fs-src> dotnet restore App.fsproj
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'restore' does not exist.
  * You intended to execute a .NET SDK command:
......

 errno 134
npm ERR! chat@0.1.0 start:fable: `dotnet fable watch fs-src`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the chat@0.1.0 start:fable script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dell/.npm/_logs/2021-05-12T20_03_58_299Z-debug.log

```
Please, what I need do?
```

**Comment by delneg** [comment]
Well, it seems like dotnet-related problem (not related to the package itself)
And frnakly I don't understand what's the exact issue here..
What directory are you running this in ?
Have you tried doing "dotnet restore" or "fable ." in "fs-src" directory ?
Also, if it doesn't work you could try to delete global.json file

**Comment by ovt00** [comment]
Thanks for the reply.
Solve: delete global.json file

Thanks

**Comment by delneg** [comment]
Deleted global.json in the repo.
